# Generated by Django 3.1.7 on 2021-04-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_auto_20210417_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=50)),
                ('delivery_run', models.CharField(choices=[('1', '1'), ('3', '2'), ('4', '3'), ('2', '4'), ('5', '5')], max_length=50)),
                ('order_stage', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('OFD', 'OFD'), ('Delivered', 'Delivered'), ('SO', 'Standing Order')], max_length=50)),
                ('archive', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.order')),
            ],
        ),
    ]
