# Generated by Django 3.1.7 on 2021-04-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_auto_20210417_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_day', models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday')], max_length=20)),
                ('delivery_run', models.CharField(choices=[('1', 'Run 1'), ('3', 'Run 2'), ('4', 'Run 3'), ('2', 'Run 4'), ('5', 'Run 5')], max_length=20)),
                ('order_stage', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('SO', 'Standing Order')], max_length=20)),
                ('archive', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.order')),
            ],
        ),
    ]
