# Generated by Django 3.1.7 on 2021-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdistribution',
            name='order_stage',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('OFD', 'OFD'), ('Delivered', 'Delivered'), ('SO', 'SO')], max_length=50),
        ),
    ]
