# Generated by Django 3.1.7 on 2021-04-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210422_1027'),
        ('distribution', '0002_auto_20210418_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdistribution',
            name='delivery_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdistribution',
            name='delivery_run',
            field=models.CharField(blank=True, choices=[('1', '1'), ('3', '2'), ('4', '3'), ('2', '4'), ('5', '5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdistribution',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
        migrations.AlterField(
            model_name='orderdistribution',
            name='order_stage',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('OFD', 'OFD'), ('Delivered', 'Delivered'), ('SO', 'SO')], max_length=50),
        ),
    ]
