# Generated by Django 3.1.7 on 2021-04-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210422_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripepayment',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
